"""Canonical roster of prominent public figures in Cono Sur news.

This module is the source of truth for high-profile politicians, judges,
and public figures from Argentina, Uruguay, and Paraguay. The glossary
feature uses these entries to override anything the LLM extracts from
headlines, so well-known figures are never mislabeled.

To add a new person, append a dict to the appropriate country block below.
Required fields: name, role, country, bio (≤140 chars, factual, in English).

Roles and biographies reflect public information at the time of writing
(early 2026). When a position changes, update the entry directly.
"""

KNOWN_PEOPLE = [
    # ════════════════════════════════════════════════════════════════════
    # ARGENTINA
    # ════════════════════════════════════════════════════════════════════

    # ── Executive (Milei government, Dec 2023–) ──
    {"name": "Javier Milei", "country": "argentina",
     "role": "President of Argentina",
     "bio": "Libertarian economist, president since December 2023, leader of La Libertad Avanza."},
    {"name": "Victoria Villarruel", "country": "argentina",
     "role": "Vice President of Argentina",
     "bio": "Lawyer, vice president since 2023, with a background in human rights and military affairs advocacy."},
    {"name": "Karina Milei", "country": "argentina",
     "role": "General Secretary of the Presidency",
     "bio": "Sister of Javier Milei and his closest political operator, leads internal party organization of LLA."},
    {"name": "Guillermo Francos", "country": "argentina",
     "role": "Chief of the Cabinet of Ministers",
     "bio": "Former Interior Minister under Milei, longtime political operator with PJ and PRO ties."},
    {"name": "Luis Caputo", "country": "argentina",
     "role": "Minister of Economy of Argentina",
     "bio": "Investment banker, finance minister under Milei; previously served as finance minister under Macri (2017-2018)."},
    {"name": "Patricia Bullrich", "country": "argentina",
     "role": "Minister of Security of Argentina",
     "bio": "Former PRO president and 2023 presidential candidate, security minister since December 2023."},
    {"name": "Luis Petri", "country": "argentina",
     "role": "Minister of Defense of Argentina",
     "bio": "UCR politician from Mendoza, defense minister under Milei since December 2023."},
    {"name": "Sandra Pettovello", "country": "argentina",
     "role": "Minister of Human Capital of Argentina",
     "bio": "Heads the merged ministry covering social development, education, labor, and health."},
    {"name": "Federico Sturzenegger", "country": "argentina",
     "role": "Minister of Deregulation and State Transformation",
     "bio": "Economist and former Central Bank president (2015-2018) under Macri, joined Milei cabinet to lead deregulation."},
    {"name": "Manuel Adorni", "country": "argentina",
     "role": "Presidential Spokesperson of Argentina",
     "bio": "Economist, daily presidential spokesperson and one of the most visible voices of the Milei administration."},
    {"name": "Santiago Caputo", "country": "argentina",
     "role": "Senior Presidential Advisor",
     "bio": "Political strategist and one of the most influential advisors in the Milei inner circle, no formal cabinet role."},
    {"name": "Gerardo Werthein", "country": "argentina",
     "role": "Minister of Foreign Affairs of Argentina",
     "bio": "Businessman and former ambassador to the United States, took over the foreign ministry in late 2024."},

    # ── Provincial Governors ──
    {"name": "Axel Kicillof", "country": "argentina",
     "role": "Governor of Buenos Aires Province",
     "bio": "Economist, Kirchnerist leader, former Minister of Economy (2013-2015), governor since 2019."},
    {"name": "Jorge Macri", "country": "argentina",
     "role": "Head of Government of the City of Buenos Aires",
     "bio": "PRO politician, cousin of Mauricio Macri, leads CABA government since December 2023."},
    {"name": "Maximiliano Pullaro", "country": "argentina",
     "role": "Governor of Santa Fe Province",
     "bio": "UCR politician, governor since December 2023, focused on security policy in Rosario."},
    {"name": "Martín Llaryora", "country": "argentina",
     "role": "Governor of Córdoba Province",
     "bio": "Peronist (Hacemos Unidos) politician, former mayor of Córdoba city, governor since December 2023."},
    {"name": "Rogelio Frigerio", "country": "argentina",
     "role": "Governor of Entre Ríos Province",
     "bio": "PRO politician, former Interior Minister under Macri, governor since December 2023."},
    {"name": "Ignacio Torres", "country": "argentina",
     "role": "Governor of Chubut Province",
     "bio": "PRO politician, governor since December 2023, prominent in disputes with the Milei government over federal funds."},
    {"name": "Gildo Insfrán", "country": "argentina",
     "role": "Governor of Formosa Province",
     "bio": "Peronist politician, longest-serving governor in Argentina, in office continuously since 1995."},

    # ── Opposition Leaders (Peronism, PRO, UCR) ──
    {"name": "Cristina Fernández de Kirchner", "country": "argentina",
     "role": "Former President of Argentina, Peronist Leader",
     "bio": "Two-term president (2007-2015), former vice president (2019-2023), leads the Kirchnerist faction of Peronism."},
    {"name": "Sergio Massa", "country": "argentina",
     "role": "Former Minister of Economy, Peronist Leader",
     "bio": "Founder of the Frente Renovador, former economy minister and 2023 presidential runner-up against Milei."},
    {"name": "Máximo Kirchner", "country": "argentina",
     "role": "National Deputy, La Cámpora Leader",
     "bio": "Son of Néstor and Cristina Kirchner, leads La Cámpora youth organization within Peronism."},
    {"name": "Mauricio Macri", "country": "argentina",
     "role": "Former President of Argentina, PRO Founder",
     "bio": "Businessman, founder of PRO, mayor of Buenos Aires (2007-2015), president (2015-2019)."},
    {"name": "Horacio Rodríguez Larreta", "country": "argentina",
     "role": "Former Head of Government of Buenos Aires City",
     "bio": "PRO politician, head of CABA government (2015-2023), 2023 presidential primary candidate."},

    # ── Congress Leadership ──
    {"name": "Martín Menem", "country": "argentina",
     "role": "President of the Chamber of Deputies of Argentina",
     "bio": "La Libertad Avanza deputy from La Rioja, nephew of former president Carlos Menem."},
    {"name": "Cristian Ritondo", "country": "argentina",
     "role": "Head of the PRO Bloc in the Chamber of Deputies",
     "bio": "PRO politician, former security minister of Buenos Aires Province under María Eugenia Vidal."},
    {"name": "Germán Martínez", "country": "argentina",
     "role": "Head of the Unión por la Patria Bloc in the Chamber of Deputies",
     "bio": "Peronist deputy from Santa Fe, leads the main opposition bloc in the lower chamber."},

    # ── Judiciary ──
    {"name": "Horacio Rosatti", "country": "argentina",
     "role": "President of the Supreme Court of Argentina",
     "bio": "Constitutional law scholar, former Justice Minister, Supreme Court Justice since 2016, court president since 2021."},
    {"name": "Carlos Rosenkrantz", "country": "argentina",
     "role": "Vice President of the Supreme Court of Argentina",
     "bio": "Constitutional lawyer and academic, Supreme Court Justice since 2016."},
    {"name": "Ricardo Lorenzetti", "country": "argentina",
     "role": "Justice of the Supreme Court of Argentina",
     "bio": "Civil law scholar, Supreme Court Justice since 2004, court president 2007-2018."},

    # ── Other Major Figures (Ex-Presidents, Governors, Business) ──
    {"name": "Alberto Fernández", "country": "argentina",
     "role": "Former President of Argentina",
     "bio": "Peronist lawyer and academic, president 2019-2023, formerly chief of cabinet under Néstor Kirchner."},
    {"name": "María Eugenia Vidal", "country": "argentina",
     "role": "Former Governor of Buenos Aires Province, PRO Politician",
     "bio": "PRO politician, governor of Buenos Aires Province 2015-2019, former national deputy."},
    {"name": "Juan Schiaretti", "country": "argentina",
     "role": "Former Governor of Córdoba Province",
     "bio": "Peronist politician, three-term governor of Córdoba, 2023 presidential candidate for Hacemos por Nuestro País."},
    {"name": "Daniel Scioli", "country": "argentina",
     "role": "Peronist Politician, Former Vice President of Argentina",
     "bio": "Former vice president (2003-2007), governor of Buenos Aires (2007-2015), and 2015 presidential candidate."},
    {"name": "Gerardo Morales", "country": "argentina",
     "role": "Former Governor of Jujuy Province, UCR Leader",
     "bio": "Radical politician, former governor of Jujuy (2015-2023), national president of the UCR."},
    {"name": "Marcos Galperín", "country": "argentina",
     "role": "Founder and CEO of Mercado Libre",
     "bio": "Argentine entrepreneur, founder of e-commerce giant Mercado Libre, prominent voice in business and tech."},

    # ════════════════════════════════════════════════════════════════════
    # URUGUAY
    # ════════════════════════════════════════════════════════════════════

    # ── Executive (Orsi government, Frente Amplio, March 2025–) ──
    {"name": "Yamandú Orsi", "country": "uruguay",
     "role": "President of Uruguay",
     "bio": "Frente Amplio politician, former Intendente of Canelones, took office March 2025."},
    {"name": "Carolina Cosse", "country": "uruguay",
     "role": "Vice President of Uruguay",
     "bio": "Engineer, former Intendenta of Montevideo, Frente Amplio, vice president since March 2025."},
    {"name": "Gabriel Oddone", "country": "uruguay",
     "role": "Minister of Economy and Finance of Uruguay",
     "bio": "Economist, partner at consultancy CPA Ferrere, took office in the Orsi cabinet in March 2025."},
    {"name": "Mario Lubetkin", "country": "uruguay",
     "role": "Minister of Foreign Affairs of Uruguay",
     "bio": "Veteran communicator and former senior FAO official, foreign minister under Orsi since March 2025."},

    # ── Frente Amplio Leadership ──
    {"name": "Fernando Pereira", "country": "uruguay",
     "role": "President of the Frente Amplio",
     "bio": "Former PIT-CNT union leader, head of the Frente Amplio political coalition."},
    {"name": "Lucía Topolansky", "country": "uruguay",
     "role": "Former Vice President of Uruguay, Frente Amplio Senator",
     "bio": "Frente Amplio elder, former vice president (2017-2020), senator and wife of José Mujica."},
    {"name": "Mario Bergara", "country": "uruguay",
     "role": "Frente Amplio Senator and Economist",
     "bio": "Economist, former president of the Central Bank of Uruguay, prominent Frente Amplio figure."},
    {"name": "Daniel Martínez", "country": "uruguay",
     "role": "Former Intendente of Montevideo, Frente Amplio Leader",
     "bio": "Engineer, former Intendente of Montevideo, Frente Amplio presidential candidate in 2019."},
    {"name": "Constanza Moreira", "country": "uruguay",
     "role": "Frente Amplio Politician and Academic",
     "bio": "Political scientist, former senator, prominent Frente Amplio intellectual."},
    {"name": "Rafael Michelini", "country": "uruguay",
     "role": "Frente Amplio Politician",
     "bio": "Veteran Frente Amplio politician, founder of Nuevo Espacio, son of senator Zelmar Michelini."},

    # ── Former Presidents (living) ──
    {"name": "Luis Lacalle Pou", "country": "uruguay",
     "role": "Former President of Uruguay",
     "bio": "Partido Nacional, president of Uruguay 2020-2025, son of former president Luis Alberto Lacalle Herrera."},
    {"name": "José Mujica", "country": "uruguay",
     "role": "Former President of Uruguay",
     "bio": "Frente Amplio, former Tupamaro, president 2010-2015, internationally recognized elder of Uruguayan left."},
    {"name": "Julio María Sanguinetti", "country": "uruguay",
     "role": "Former President of Uruguay",
     "bio": "Partido Colorado, two-term president (1985-1990, 1995-2000), key figure in Uruguay's return to democracy."},
    {"name": "Luis Alberto Lacalle Herrera", "country": "uruguay",
     "role": "Former President of Uruguay",
     "bio": "Partido Nacional, president 1990-1995, father of former president Luis Lacalle Pou."},

    # ── Lacalle Pou Era Cabinet (2020-2025, still public figures) ──
    {"name": "Álvaro Delgado", "country": "uruguay",
     "role": "Partido Nacional Leader, Former Secretary of the Presidency",
     "bio": "Veterinarian, secretary of the presidency under Lacalle Pou, Partido Nacional 2024 presidential candidate."},
    {"name": "Beatriz Argimón", "country": "uruguay",
     "role": "Former Vice President of Uruguay",
     "bio": "Lawyer, Partido Nacional politician, vice president of Uruguay 2020-2025."},
    {"name": "Azucena Arbeleche", "country": "uruguay",
     "role": "Former Minister of Economy and Finance of Uruguay",
     "bio": "Economist, finance minister under Luis Lacalle Pou (2020-2025)."},
    {"name": "Javier García", "country": "uruguay",
     "role": "Former Minister of National Defense of Uruguay",
     "bio": "Partido Nacional politician, defense minister under Luis Lacalle Pou (2020-2025)."},
    {"name": "Luis Alberto Heber", "country": "uruguay",
     "role": "Partido Nacional Politician, Former Minister of Interior",
     "bio": "Veteran Partido Nacional politician, former minister of transport and later interior under Lacalle Pou."},
    {"name": "Pablo Mieres", "country": "uruguay",
     "role": "Partido Independiente Leader",
     "bio": "Lawyer, founder and historic leader of Partido Independiente, former Minister of Labor under Lacalle Pou."},

    # ── Opposition Leaders (post-2025) ──
    {"name": "Andrés Ojeda", "country": "uruguay",
     "role": "Partido Colorado Leader",
     "bio": "Lawyer, Partido Colorado 2024 presidential candidate, prominent opposition voice."},
    {"name": "Guido Manini Ríos", "country": "uruguay",
     "role": "Cabildo Abierto Leader, Senator",
     "bio": "Retired army general, founder of right-wing Cabildo Abierto party, senator since 2020."},
    {"name": "Pablo Da Silveira", "country": "uruguay",
     "role": "Former Minister of Education and Culture of Uruguay",
     "bio": "Philosopher and academic, Partido Nacional, education minister under Lacalle Pou (2020-2025)."},
    {"name": "Óscar Andrade", "country": "uruguay",
     "role": "Frente Amplio Senator",
     "bio": "Former construction workers' union leader (SUNCA), Communist Party member, Frente Amplio senator."},
    {"name": "Daniel Caggiani", "country": "uruguay",
     "role": "Frente Amplio Senator",
     "bio": "Frente Amplio politician affiliated with the MPP, former Mercosur parliamentarian and senator."},
    {"name": "Graciela Bianchi", "country": "uruguay",
     "role": "Partido Nacional Senator",
     "bio": "Lawyer and educator, Partido Nacional senator close to Luis Lacalle Pou, vocal opposition voice."},
    {"name": "Pedro Bordaberry", "country": "uruguay",
     "role": "Partido Colorado Politician",
     "bio": "Lawyer, Partido Colorado leader, former senator and minister, son of former president Juan María Bordaberry."},
    {"name": "Liliam Kechichián", "country": "uruguay",
     "role": "Frente Amplio Senator, Former Minister of Tourism",
     "bio": "Frente Amplio politician, tourism minister 2015-2020, senator and prominent voice within the coalition."},
    {"name": "Sebastián Da Silva", "country": "uruguay",
     "role": "Partido Nacional Senator",
     "bio": "Rancher and Partido Nacional senator, vocal voice on rural and agricultural policy."},

    # ════════════════════════════════════════════════════════════════════
    # PARAGUAY
    # ════════════════════════════════════════════════════════════════════

    # ── Executive (Peña government, ANR/Colorado, Aug 2023–) ──
    {"name": "Santiago Peña", "country": "paraguay",
     "role": "President of Paraguay",
     "bio": "Economist, former finance minister, president since August 2023, ANR (Partido Colorado)."},
    {"name": "Pedro Alliana", "country": "paraguay",
     "role": "Vice President of Paraguay",
     "bio": "ANR politician, former president of the Colorado Party, vice president since August 2023."},
    {"name": "Carlos Fernández Valdovinos", "country": "paraguay",
     "role": "Minister of Economy and Finance of Paraguay",
     "bio": "Economist and former Central Bank president, minister of economy under Peña since August 2023."},
    {"name": "Rubén Ramírez Lezcano", "country": "paraguay",
     "role": "Minister of Foreign Affairs of Paraguay",
     "bio": "Career diplomat, foreign minister under Peña; previously served as foreign minister under Nicanor Duarte Frutos."},

    # ── ANR / Colorado Party Leaders ──
    {"name": "Horacio Cartes", "country": "paraguay",
     "role": "Former President of Paraguay, ANR Honor Colorado Leader",
     "bio": "Tobacco businessman, president of Paraguay 2013-2018, leads the Honor Colorado faction of the ANR."},
    {"name": "Mario Abdo Benítez", "country": "paraguay",
     "role": "Former President of Paraguay",
     "bio": "ANR politician, president of Paraguay 2018-2023, leads the Fuerza Republicana faction within the Colorado Party."},
    {"name": "Lilian Samaniego", "country": "paraguay",
     "role": "ANR Senator",
     "bio": "Veteran Colorado Party politician, multiple-term senator and former ANR party president."},
    {"name": "Silvio Ovelar", "country": "paraguay",
     "role": "ANR Senator",
     "bio": "Colorado Party senator, longtime parliamentary figure aligned with the Cartes wing."},
    {"name": "Basilio Núñez", "country": "paraguay",
     "role": "ANR Senator",
     "bio": "Colorado Party senator known as 'Bachi' Núñez, prominent legislative leader of the ANR."},
    {"name": "Hugo Velázquez", "country": "paraguay",
     "role": "Former Vice President of Paraguay",
     "bio": "ANR politician, vice president 2018-2022, designated as significantly corrupt by the U.S. State Department in 2022."},

    # ── Former Presidents (living) ──
    {"name": "Federico Franco", "country": "paraguay",
     "role": "Former President of Paraguay",
     "bio": "Surgeon, PLRA politician, president 2012-2013 after the impeachment of Fernando Lugo."},
    {"name": "Fernando Lugo", "country": "paraguay",
     "role": "Former President of Paraguay",
     "bio": "Former Catholic bishop, president 2008-2012, leader of Frente Guasú left-wing coalition."},
    {"name": "Nicanor Duarte Frutos", "country": "paraguay",
     "role": "Former President of Paraguay",
     "bio": "ANR politician, president of Paraguay 2003-2008."},
    {"name": "Juan Carlos Wasmosy", "country": "paraguay",
     "role": "Former President of Paraguay",
     "bio": "Civil engineer and businessman, ANR, first civilian president after the Stroessner regime (1993-1998)."},

    # ── Opposition Leaders ──
    {"name": "Efraín Alegre", "country": "paraguay",
     "role": "PLRA Leader",
     "bio": "Lawyer, leader of the Partido Liberal Radical Auténtico, multiple-time presidential candidate."},
    {"name": "Esperanza Martínez", "country": "paraguay",
     "role": "Frente Guasú Senator",
     "bio": "Doctor, former Minister of Public Health under Fernando Lugo, senator for Frente Guasú."},
    {"name": "Soledad Núñez", "country": "paraguay",
     "role": "Opposition Leader",
     "bio": "Engineer, former Minister of Housing, 2023 presidential candidate for the Concertación opposition coalition."},
    {"name": "Sebastián Villarejo", "country": "paraguay",
     "role": "Cruzada Nacional Leader",
     "bio": "Lawyer, founding leader of right-wing party Cruzada Nacional and prominent opposition voice."},
    {"name": "Kattya González", "country": "paraguay",
     "role": "Former Senator, Opposition Figure",
     "bio": "Lawyer, former Encuentro Nacional senator expelled from the Senate in early 2024, prominent anti-corruption voice."},
    {"name": "Yolanda Paredes", "country": "paraguay",
     "role": "Cruzada Nacional Senator",
     "bio": "Cruzada Nacional senator, opposition figure aligned with Sebastián Villarejo."},
    {"name": "Sixto Pereira", "country": "paraguay",
     "role": "Frente Guasú Senator",
     "bio": "Veteran Frente Guasú senator, longtime left-wing political figure."},
    {"name": "Carlos Filizzola", "country": "paraguay",
     "role": "Frente Guasú Senator, Former Mayor of Asunción",
     "bio": "Doctor, former mayor of Asunción (1996-2001), former Interior Minister under Lugo, Frente Guasú senator."},
    {"name": "Blas Llano", "country": "paraguay",
     "role": "PLRA Senator",
     "bio": "Veteran Liberal politician, longtime senator and former president of the PLRA."},
    {"name": "Eduardo Nakayama", "country": "paraguay",
     "role": "PLRA Politician",
     "bio": "Lawyer, prominent Asunción Liberal politician and 2023 Asunción mayoral candidate for the Concertación opposition."},
    {"name": "Miguel Prieto", "country": "paraguay",
     "role": "Mayor of Ciudad del Este",
     "bio": "Yo Creo movement leader, mayor of Ciudad del Este, prominent independent figure outside the two main parties."},
    {"name": "Jorge Querey", "country": "paraguay",
     "role": "Frente Guasú Senator",
     "bio": "Frente Guasú senator and longtime left-wing political figure within the coalition."},
]
